Fixed postgres variables
-file=/keycloak/postgres/env-postgres-psql -e PGDATA=/var/lib/postgresql/data/pgdata -v /keycloak/postgres/data:/var/lib/postgresql/data:rw -v /etc/passwd:/etc/passwd:ro postgres:12.2-alpine
chmod: /var/run/postgresql: Operation not permitted
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html

 sudo docker run --rm --name keycloak-postgres --log-driver=none --tmpfs=/tmp:rw,noexec,nosuid,size=100m --network=keycloak-network --user=995:995 --env-file=/keycloak/postgres/env-postgres-psql -e PGDATA=/var/lib/postgresql/data/pgdata -v /keycloak/postgres/data:/var/lib/postgresql/data:rw -v /etc/passwd:/etc/passwd:ro postgres:12.2-alpine

sudo docker run --rm --name keycloak-postgres --log-driver=none --tmpfs=/tmp:rw,noexec,nosuid,size=100m --network=keycloak-network --user=995:995 --env-file=/keycloak/postgres/env-postgres-psql -e PGDATA=/var/lib/postgresql/data/pgdata -v /keycloak/postgres/data:/var/lib/postgresql/data:rw -v /etc/passwd:/etc/passwd:ro postgres:12.2-alpine
chmod: /var/run/postgresql: Operation not permitted
The files belonging to this database system will be owned by user "keycloak".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
2020-04-03 23:34:22.714 UTC [21] WARNING:  no usable system locales were found
ok
syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data/pgdata -l logfile start

waiting for server to start....2020-04-03 23:34:23.296 UTC [26] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
2020-04-03 23:34:23.299 UTC [26] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-04-03 23:34:23.315 UTC [27] LOG:  database system was shut down at 2020-04-03 23:34:23 UTC
2020-04-03 23:34:23.318 UTC [26] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....2020-04-03 23:34:23.473 UTC [26] LOG:  received fast shutdown request
2020-04-03 23:34:23.475 UTC [26] LOG:  aborting any active transactions
2020-04-03 23:34:23.475 UTC [26] LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
2020-04-03 23:34:23.476 UTC [28] LOG:  shutting down
2020-04-03 23:34:23.487 UTC [26] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2020-04-03 23:34:23.582 UTC [1] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
2020-04-03 23:34:23.582 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-04-03 23:34:23.582 UTC [1] LOG:  listening on IPv6 address "::", port 5432

Fixed keycloak permissions

docker run --rm --name keycloak --log-driver=none -e KEYCLOAK_USER=keycloak -e KEYCLOAK_PASSWORD=keycloak-synapse --user=995:995 -e PROXY_ADDRESS_FORWARDING=true -p 8442:8080 -v /etc/letsencrypt/live/keycloak/cert.pem:/etc/x509/https/tls.crt:ro -v /etc/letsencrypt/live/keycloak/key.pem:/etc/x509/https/tls.key:ro -v /etc/passwd:/etc/passwd:ro --net keycloak-network -e DB_USER=keycloak -e DB_PASSWORD=keycloak jboss/keycloak:9.0.2
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create?name=keycloak: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
ubuntu@ip-172-31-13-183:~$ sudo docker run --rm --name keycloak --log-driver=none -e KEYCLOAK_USER=keycloak -e KEYCLOAK_PASSWORD=keycloak-synapse --user=995:995 -e PROXY_ADDRESS_FORWARDING=true -p 8442:8080 -v /etc/letsencrypt/live/keycloak/cert.pem:/etc/x509/https/tls.crt:ro -v /etc/letsencrypt/live/keycloak/key.pem:/etc/x509/https/tls.key:ro -v /etc/passwd:/etc/passwd:ro --net keycloak-network -e DB_USER=keycloak -e DB_PASSWORD=keycloak jboss/keycloak:9.0.2
/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json (Permission denied)

Make service files own by root